version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env

  web:
    build: ./webapp
    ports:
      - "8080:8080"
    env_file:
      - ./webapp/.env
